import asyncio
import unittest
from contextlib import asynccontextmanager
from datetime import datetime
from unittest.mock import AsyncMock, patch

from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, insert, select, text
from sqlalchemy.orm import Session

from app.core.config import Settings
from app.core.dashboard_database import DashboardBase
from app.core.database import Base
from app.core.db_resources import ReadOnlySession
from app.db.data_transfer import copy_table
from app.db.migrations import ensure_schema_current, migration_config
from app.models.class_preferences import ClassStar
from app.models.dmoj import AuthUser, JudgeProblem, JudgeProblemGroup, JudgeProblemtype
from app.models.ai_tag import JudgeProblemAiTag
from app.services.auto_tag_service import AutoTagService, TagOutcome
from app.schemas.ai import AutoTagResult
import app.models.dashboard
from db_fixtures import create_source_tables


class MigrationTests(unittest.TestCase):
    def setUp(self):
        self.engine = create_engine("sqlite://")

    def tearDown(self):
        self.engine.dispose()

    def test_fresh_upgrade_check_downgrade_and_reupgrade(self):
        with self.engine.begin() as connection:
            config = migration_config(connection)
            command.upgrade(config, "head")
            command.check(config)
            self.assertEqual(set(inspect(connection).get_table_names()),
                             set(DashboardBase.metadata.tables) | {"alembic_version"})
            self.assertEqual(connection.execute(text("SELECT version_num FROM alembic_version")).scalar(),
                             "20261003_0001")
            self.assertEqual(ScriptDirectory.from_config(config).get_heads(), ["20261003_0001"])
            command.downgrade(config, "base")
            self.assertEqual(set(inspect(connection).get_table_names()), {"alembic_version"})
            command.upgrade(config, "head")
            command.check(config)

    def test_baseline_adopts_existing_star_without_losing_data(self):
        ClassStar.__table__.create(self.engine)
        timestamp = datetime(2026, 1, 1, microsecond=123456)
        with self.engine.begin() as connection:
            connection.execute(ClassStar.__table__.insert(), dict(owner_profile_id=2, organization_id=9, starred_at=timestamp))
            command.upgrade(migration_config(connection), "head")
            self.assertEqual(connection.execute(select(ClassStar.starred_at)).scalar(), timestamp)

    def test_baseline_rejects_incompatible_existing_table(self):
        with self.engine.begin() as connection:
            connection.execute(text("CREATE TABLE class_star (wrong_id INTEGER PRIMARY KEY)"))
            with self.assertRaisesRegex(RuntimeError, "does not match"):
                command.upgrade(migration_config(connection), "head")

    def test_check_detects_unversioned_schema_drift(self):
        with self.engine.begin() as connection:
            command.upgrade(migration_config(connection), "head")
            connection.execute(text("ALTER TABLE class_star ADD COLUMN unexpected TEXT"))
            with self.assertRaises(AutogenerateDiffsDetected):
                command.check(migration_config(connection))

    def test_startup_checks_version_without_creating_tables(self):
        with self.engine.connect() as connection:
            class AsyncConnection:
                async def run_sync(self, callback):
                    return callback(connection)
            class AsyncEngine:
                @asynccontextmanager
                async def connect(self):
                    yield AsyncConnection()
            with self.assertRaisesRegex(RuntimeError, "schema is outdated"):
                asyncio.run(ensure_schema_current(AsyncEngine()))
            self.assertEqual(inspect(connection).get_table_names(), [])
            command.upgrade(migration_config(connection), "head")
            asyncio.run(ensure_schema_current(AsyncEngine()))


class DatabaseBoundaryTests(unittest.TestCase):
    def test_owned_models_are_separate_and_have_no_source_foreign_keys(self):
        self.assertEqual(set(DashboardBase.metadata.tables),
                         {"class_star", "tmath_virtual_class_session", "judge_problem_ai_tag"})
        self.assertFalse(set(Base.metadata.tables) & set(DashboardBase.metadata.tables))
        self.assertTrue(all(not table.foreign_keys for table in DashboardBase.metadata.tables.values()))

    def test_connections_have_independent_hosts_ports_credentials_and_safe_urls(self):
        settings = Settings(_env_file=None, PROJECT_NAME="test", SOURCE_DB_HOST="source-server", SOURCE_DB_PORT=3306,
                            SOURCE_DB_USER="reader", SOURCE_DB_PASSWORD="source@password:/%", SOURCE_DB_NAME="source",
                            DASHBOARD_DB_HOST="dashboard-server", DASHBOARD_DB_PORT=3307, DASHBOARD_DB_USER="app",
                            DASHBOARD_DB_PASSWORD="dashboard@password:/%", DASHBOARD_DB_NAME="dashboard",
                            DASHBOARD_MIGRATION_USER="migrator", DASHBOARD_MIGRATION_PASSWORD="migration-password")
        self.assertEqual((settings.source_database_url.host, settings.source_database_url.port), ("source-server", 3306))
        self.assertEqual((settings.dashboard_database_url.host, settings.dashboard_database_url.port), ("dashboard-server", 3307))
        self.assertEqual(settings.dashboard_database_url.password, "dashboard@password:/%")
        self.assertEqual(settings.dashboard_migration_url.username, "migrator")
        self.assertEqual(settings.source_database_url.password, "source@password:/%")

    def test_source_orm_session_rejects_writes(self):
        engine = create_engine("sqlite://")
        try:
            AuthUser.__table__.create(engine)
            with ReadOnlySession(engine) as session:
                session.add(AuthUser(id=1, username="should-not-exist"))
                with self.assertRaisesRegex(RuntimeError, "read-only"):
                    session.flush()
            with engine.connect() as connection:
                self.assertEqual(connection.execute(select(AuthUser.id)).all(), [])
        finally:
            engine.dispose()


class TransferTests(unittest.TestCase):
    def test_verified_copy_is_retryable_and_rejects_conflicting_data(self):
        source = create_engine("sqlite://")
        target = create_engine("sqlite://")
        try:
            for engine in (source, target):
                ClassStar.__table__.create(engine)
            timestamp = datetime(2026, 1, 1, microsecond=999999)
            with source.begin() as connection:
                connection.execute(ClassStar.__table__.insert(), [
                    dict(owner_profile_id=2, organization_id=i, starred_at=timestamp) for i in range(1, 4)
                ])
            with source.connect() as read, target.begin() as write:
                for apply in (False, True, True):
                    self.assertEqual(copy_table(read, write, ClassStar.__table__, ClassStar.__table__,
                                                apply=apply, batch_size=2), 3)
                self.assertEqual(len(write.execute(select(ClassStar)).all()), 3)
                write.execute(ClassStar.__table__.update().where(ClassStar.organization_id == 1)
                              .values(starred_at=datetime(2025, 1, 1)))
                with self.assertRaisesRegex(ValueError, "Conflicting row"):
                    copy_table(read, write, ClassStar.__table__, ClassStar.__table__, apply=True)
        finally:
            source.dispose()
            target.dispose()


class AsyncSessionAdapter:
    def __init__(self, session):
        self.session = session
    async def execute(self, statement):
        return self.session.execute(statement)
    def add(self, instance):
        self.session.add(instance)
    async def commit(self):
        self.session.commit()
    async def rollback(self):
        self.session.rollback()


class AutoTagBoundaryTests(unittest.IsolatedAsyncioTestCase):
    async def test_worker_writes_dashboard_and_skips_already_tagged_source_problems(self):
        source = create_engine("sqlite://")
        dashboard = create_engine("sqlite://")
        try:
            create_source_tables(source, JudgeProblem, JudgeProblemtype, JudgeProblemGroup)
            JudgeProblemAiTag.__table__.create(dashboard)
            with source.begin() as connection:
                connection.execute(insert(JudgeProblem.__table__), dict(id=1, code="p1", name="Bài toán 1"))
                connection.execute(insert(JudgeProblemtype.__table__), dict(id=1, name="tag", full_name="Chủ đề 1"))
                connection.execute(insert(JudgeProblemGroup.__table__), dict(id=4, name="A", full_name="Ghi nhớ"))
            with ReadOnlySession(source) as read, Session(dashboard) as write:
                @asynccontextmanager
                async def source_session():
                    yield AsyncSessionAdapter(read)
                @asynccontextmanager
                async def dashboard_session():
                    yield AsyncSessionAdapter(write)
                result = AutoTagResult(problem_id=1, primary_tag_id=1, secondary_tag_ids=[],
                                       bloom_group_id=4, reasoning="Test kết nối")
                service = AutoTagService()
                service.tag_problem = AsyncMock(return_value=TagOutcome(result, "llm", result))
                with patch("app.services.auto_tag_service.AsyncSessionLocal", source_session), \
                     patch("app.services.auto_tag_service.DashboardSessionLocal", dashboard_session), \
                     patch("app.services.auto_tag_service.asyncio.sleep", new=AsyncMock()):
                    await service.run_batch_process(1)
                    await service.run_batch_process(1)
                service.tag_problem.assert_awaited_once()
                self.assertEqual(write.execute(select(JudgeProblemAiTag.problem_id)).scalars().all(), [1])
                self.assertEqual(read.execute(select(JudgeProblem.id)).scalars().all(), [1])
        finally:
            source.dispose()
            dashboard.dispose()

    async def test_status_combines_two_databases_and_handles_missing_source_problem(self):
        source = create_engine("sqlite://")
        dashboard = create_engine("sqlite://")
        try:
            create_source_tables(source, JudgeProblem, JudgeProblemtype, JudgeProblemGroup)
            JudgeProblemAiTag.__table__.create(dashboard)
            with Session(source) as read, Session(dashboard) as write:
                read.execute(insert(JudgeProblem.__table__), dict(id=1, code="p1", name="Bài toán 1"))
                read.execute(insert(JudgeProblemtype.__table__), dict(id=1, name="tag", full_name="Chủ đề 1"))
                read.execute(insert(JudgeProblemGroup.__table__), dict(id=4, name="A", full_name="Ghi nhớ"))
                read.commit()
                for problem_id in (1, 999):
                    write.add(JudgeProblemAiTag(problem_id=problem_id, primary_tag_id=1, bloom_group_id=4))
                write.commit()
                result = await AutoTagService().get_tagging_status(AsyncSessionAdapter(read), AsyncSessionAdapter(write))
                self.assertEqual(result["total_problems"], 1)
                self.assertEqual(result["tagged_problems"], 1)
                self.assertEqual(result["progress_percentage"], 100.0)
                known = next(tag for tag in result["recent_tags"] if tag["problem_id"] == 1)
                self.assertEqual((known["problem_code"], known["primary_tag_name"], known["bloom_group_name"]),
                                 ("p1", "Chủ đề 1", "Ghi nhớ"))
                self.assertEqual(len(result["recent_tags"]), 2)
        finally:
            source.dispose()
            dashboard.dispose()
